[package]
name = "rgbd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
directories = "5.0.1"
ureq = "2.9.7"
url = "2.5.0"
